name: final_project_cs3520

on: [push]

env:
  EXE_NAME: final_project_cs3520

jobs:
  build:
    name: Project_Building
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:

      - name: Checkout project repo from GitHub
        uses: actions/checkout@v1

      - name: Executable name Environment Variable Check
        run: |
          echo $EXE_NAME
          echo " "
          echo ${{runner.workspace}}
          echo " "
          echo $GITHUB_WORKSPACE
          echo " "
          g++ --version
          cmake --version
          sudo apt-get install libx11-dev libxrandr-dev
          sudo apt-get install libgl1-mesa-dev

      - name: Create build environment
        #run: cmake -E make_directory ${{runner.workspace}}/build
        run:  mkdir ${{runner.workspace}}/build

      - name: Configure the build
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build the project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build .

      - name: Run the project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # NOTE: You may need to update the path to your sample files
        # in this command.
        run: ./$EXE_NAME -t
